# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' Hello ctlars from your C++ friends :).
#'
#' @name
#' hello_ctlars_from_Cpp
#'
#' @description
#' This function returns a greeting message.
#'
#' @return A string with "Hello, ctlars!".
#'
#' @export
NULL

hello_ctlars_from_Cpp <- function() {
    .Call(`_ctlars_hello_ctlars_from_Cpp`)
}

